"""Initial migration with all models

Revision ID: c0a0c074cf92
Revises: 
Create Date: 2025-11-04 14:43:54.573587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0a0c074cf92'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False, comment="Configuration key (e.g., 'matching.time_window_hours')"),
    sa.Column('value', sa.Text(), nullable=False, comment='Configuration value (stored as string, parse as needed)'),
    sa.Column('value_type', sa.String(length=50), nullable=False, comment="Data type hint (e.g., 'string', 'int', 'float', 'bool', 'json')"),
    sa.Column('description', sa.Text(), nullable=True, comment='Human-readable description of this configuration'),
    sa.Column('category', sa.String(length=100), nullable=True, comment="Configuration category (e.g., 'matching', 'email', 'retention')"),
    sa.Column('is_sensitive', sa.Boolean(), nullable=False, comment='Whether this config contains sensitive data (e.g., API keys)'),
    sa.Column('is_editable', sa.Boolean(), nullable=False, comment='Whether this config can be edited via UI/API'),
    sa.Column('created_by', sa.String(length=255), nullable=True, comment='User or system that created this config'),
    sa.Column('updated_by', sa.String(length=255), nullable=True, comment='User or system that last updated this config'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_config_category', 'config', ['category'], unique=False)
    op.create_index(op.f('ix_config_category'), 'config', ['category'], unique=False)
    op.create_index(op.f('ix_config_key'), 'config', ['key'], unique=True)
    op.create_table('emails',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('message_id', sa.String(length=255), nullable=False, comment='Unique email message ID from IMAP'),
    sa.Column('sender', sa.String(length=255), nullable=False, comment='Email sender address'),
    sa.Column('subject', sa.String(length=500), nullable=False, comment='Email subject line'),
    sa.Column('body', sa.Text(), nullable=False, comment='Full email body (HTML or plain text)'),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True, comment='Parsed transaction amount'),
    sa.Column('currency', sa.String(length=3), nullable=True, comment='Currency code (ISO 4217, e.g., NGN, USD)'),
    sa.Column('reference', sa.String(length=255), nullable=True, comment='Transaction reference or ID from email'),
    sa.Column('account_info', sa.String(length=255), nullable=True, comment='Account number or masked account info'),
    sa.Column('email_timestamp', sa.DateTime(timezone=True), nullable=True, comment='Transaction timestamp extracted from email'),
    sa.Column('parsed_at', sa.DateTime(timezone=True), nullable=False, comment='When this email was parsed by the system'),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False, comment='When this email was received (from email headers)'),
    sa.Column('parsing_confidence', sa.Numeric(precision=5, scale=4), nullable=True, comment='Confidence score for parsing accuracy (0-1)'),
    sa.Column('is_processed', sa.Boolean(), nullable=False, comment='Whether this email has been processed for matching'),
    sa.Column('processing_error', sa.Text(), nullable=True, comment='Any error encountered during processing'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_email_amount_timestamp', 'emails', ['amount', 'email_timestamp'], unique=False)
    op.create_index('idx_email_processed', 'emails', ['is_processed', 'parsed_at'], unique=False)
    op.create_index(op.f('ix_emails_amount'), 'emails', ['amount'], unique=False)
    op.create_index(op.f('ix_emails_email_timestamp'), 'emails', ['email_timestamp'], unique=False)
    op.create_index(op.f('ix_emails_is_processed'), 'emails', ['is_processed'], unique=False)
    op.create_index(op.f('ix_emails_message_id'), 'emails', ['message_id'], unique=True)
    op.create_index(op.f('ix_emails_reference'), 'emails', ['reference'], unique=False)
    op.create_table('logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False, comment="Log level (e.g., 'DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL')"),
    sa.Column('event', sa.String(length=100), nullable=False, comment="Event type or category (e.g., 'email_fetch', 'matching', 'api_call')"),
    sa.Column('message', sa.Text(), nullable=False, comment='Log message'),
    sa.Column('component', sa.String(length=100), nullable=True, comment="Component that generated the log (e.g., 'email_fetcher', 'matcher')"),
    sa.Column('request_id', sa.String(length=100), nullable=True, comment='Request ID for tracing (from x-request-id header)'),
    sa.Column('user_id', sa.String(length=255), nullable=True, comment='User ID if applicable'),
    sa.Column('details', sa.Text(), nullable=True, comment='JSON blob with additional context'),
    sa.Column('exception', sa.Text(), nullable=True, comment='Exception traceback if this is an error log'),
    sa.Column('email_id', sa.Integer(), nullable=True, comment='Related email ID if applicable'),
    sa.Column('transaction_id', sa.Integer(), nullable=True, comment='Related transaction ID if applicable'),
    sa.Column('match_id', sa.Integer(), nullable=True, comment='Related match ID if applicable'),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False, comment='When this log entry was created'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_log_component_level', 'logs', ['component', 'level'], unique=False)
    op.create_index('idx_log_event_timestamp', 'logs', ['event', 'timestamp'], unique=False)
    op.create_index('idx_log_level_timestamp', 'logs', ['level', 'timestamp'], unique=False)
    op.create_index(op.f('ix_logs_component'), 'logs', ['component'], unique=False)
    op.create_index(op.f('ix_logs_email_id'), 'logs', ['email_id'], unique=False)
    op.create_index(op.f('ix_logs_event'), 'logs', ['event'], unique=False)
    op.create_index(op.f('ix_logs_level'), 'logs', ['level'], unique=False)
    op.create_index(op.f('ix_logs_match_id'), 'logs', ['match_id'], unique=False)
    op.create_index(op.f('ix_logs_request_id'), 'logs', ['request_id'], unique=False)
    op.create_index(op.f('ix_logs_timestamp'), 'logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_logs_transaction_id'), 'logs', ['transaction_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.String(length=255), nullable=False, comment='Unique transaction ID from external system'),
    sa.Column('external_source', sa.String(length=100), nullable=False, comment="Source system (e.g., 'paystack', 'flutterwave', 'manual')"),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False, comment='Transaction amount'),
    sa.Column('currency', sa.String(length=3), nullable=False, comment='Currency code (ISO 4217)'),
    sa.Column('transaction_type', sa.String(length=50), nullable=True, comment="Type of transaction (e.g., 'credit', 'debit', 'transfer')"),
    sa.Column('account_ref', sa.String(length=255), nullable=True, comment='Account reference or identifier'),
    sa.Column('description', sa.Text(), nullable=True, comment='Transaction description or narration'),
    sa.Column('reference', sa.String(length=255), nullable=True, comment='Transaction reference code'),
    sa.Column('customer_name', sa.String(length=255), nullable=True, comment='Customer or sender name'),
    sa.Column('customer_email', sa.String(length=255), nullable=True, comment='Customer email address'),
    sa.Column('transaction_timestamp', sa.DateTime(timezone=True), nullable=False, comment='When the transaction occurred'),
    sa.Column('polled_at', sa.DateTime(timezone=True), nullable=False, comment='When this transaction was fetched by the poller'),
    sa.Column('status', sa.String(length=50), nullable=False, comment="Transaction status (e.g., 'pending', 'verified', 'failed')"),
    sa.Column('is_verified', sa.Boolean(), nullable=False, comment='Whether this transaction has been verified via email match'),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True, comment='When this transaction was verified'),
    sa.Column('raw_data', sa.Text(), nullable=True, comment='JSON blob of raw API response'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_transaction_amount_timestamp', 'transactions', ['amount', 'transaction_timestamp'], unique=False)
    op.create_index('idx_transaction_source_status', 'transactions', ['external_source', 'status'], unique=False)
    op.create_index('idx_transaction_verified', 'transactions', ['is_verified', 'status'], unique=False)
    op.create_index(op.f('ix_transactions_account_ref'), 'transactions', ['account_ref'], unique=False)
    op.create_index(op.f('ix_transactions_amount'), 'transactions', ['amount'], unique=False)
    op.create_index(op.f('ix_transactions_external_source'), 'transactions', ['external_source'], unique=False)
    op.create_index(op.f('ix_transactions_is_verified'), 'transactions', ['is_verified'], unique=False)
    op.create_index(op.f('ix_transactions_reference'), 'transactions', ['reference'], unique=False)
    op.create_index(op.f('ix_transactions_status'), 'transactions', ['status'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_id'), 'transactions', ['transaction_id'], unique=True)
    op.create_index(op.f('ix_transactions_transaction_timestamp'), 'transactions', ['transaction_timestamp'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email_id', sa.Integer(), nullable=False, comment='Reference to the email record'),
    sa.Column('transaction_id', sa.Integer(), nullable=True, comment='Reference to the matched transaction (null if unmatched)'),
    sa.Column('matched', sa.Boolean(), nullable=False, comment='Whether a match was found'),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False, comment='Match confidence score (0-1)'),
    sa.Column('match_method', sa.String(length=100), nullable=True, comment="Method used for matching (e.g., 'exact', 'fuzzy', 'heuristic')"),
    sa.Column('match_details', sa.Text(), nullable=True, comment='JSON blob with detailed matching breakdown (scores per rule)'),
    sa.Column('alternative_matches', sa.Text(), nullable=True, comment='JSON array of other candidate matches with lower confidence'),
    sa.Column('status', sa.String(length=50), nullable=False, comment="Match status (e.g., 'pending', 'confirmed', 'rejected', 'review')"),
    sa.Column('reviewed_by', sa.String(length=255), nullable=True, comment='User or system that reviewed this match'),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True, comment='When this match was reviewed'),
    sa.Column('review_notes', sa.Text(), nullable=True, comment='Notes from manual review'),
    sa.Column('matched_at', sa.DateTime(timezone=True), nullable=False, comment='When this match was created'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_match_confidence', 'matches', ['matched', 'confidence'], unique=False)
    op.create_index('idx_match_email_transaction', 'matches', ['email_id', 'transaction_id'], unique=False)
    op.create_index('idx_match_status', 'matches', ['status', 'matched_at'], unique=False)
    op.create_index(op.f('ix_matches_confidence'), 'matches', ['confidence'], unique=False)
    op.create_index(op.f('ix_matches_email_id'), 'matches', ['email_id'], unique=False)
    op.create_index(op.f('ix_matches_matched'), 'matches', ['matched'], unique=False)
    op.create_index(op.f('ix_matches_status'), 'matches', ['status'], unique=False)
    op.create_index(op.f('ix_matches_transaction_id'), 'matches', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_matches_transaction_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_status'), table_name='matches')
    op.drop_index(op.f('ix_matches_matched'), table_name='matches')
    op.drop_index(op.f('ix_matches_email_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_confidence'), table_name='matches')
    op.drop_index('idx_match_status', table_name='matches')
    op.drop_index('idx_match_email_transaction', table_name='matches')
    op.drop_index('idx_match_confidence', table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_transactions_transaction_timestamp'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_transaction_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_status'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_reference'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_is_verified'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_external_source'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_amount'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_account_ref'), table_name='transactions')
    op.drop_index('idx_transaction_verified', table_name='transactions')
    op.drop_index('idx_transaction_source_status', table_name='transactions')
    op.drop_index('idx_transaction_amount_timestamp', table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_logs_transaction_id'), table_name='logs')
    op.drop_index(op.f('ix_logs_timestamp'), table_name='logs')
    op.drop_index(op.f('ix_logs_request_id'), table_name='logs')
    op.drop_index(op.f('ix_logs_match_id'), table_name='logs')
    op.drop_index(op.f('ix_logs_level'), table_name='logs')
    op.drop_index(op.f('ix_logs_event'), table_name='logs')
    op.drop_index(op.f('ix_logs_email_id'), table_name='logs')
    op.drop_index(op.f('ix_logs_component'), table_name='logs')
    op.drop_index('idx_log_level_timestamp', table_name='logs')
    op.drop_index('idx_log_event_timestamp', table_name='logs')
    op.drop_index('idx_log_component_level', table_name='logs')
    op.drop_table('logs')
    op.drop_index(op.f('ix_emails_reference'), table_name='emails')
    op.drop_index(op.f('ix_emails_message_id'), table_name='emails')
    op.drop_index(op.f('ix_emails_is_processed'), table_name='emails')
    op.drop_index(op.f('ix_emails_email_timestamp'), table_name='emails')
    op.drop_index(op.f('ix_emails_amount'), table_name='emails')
    op.drop_index('idx_email_processed', table_name='emails')
    op.drop_index('idx_email_amount_timestamp', table_name='emails')
    op.drop_table('emails')
    op.drop_index(op.f('ix_config_key'), table_name='config')
    op.drop_index(op.f('ix_config_category'), table_name='config')
    op.drop_index('idx_config_category', table_name='config')
    op.drop_table('config')
    # ### end Alembic commands ###
